import { useState } from 'react';
import type { Tool, Material } from '../../types/analysis';
import Card from '../ui/Card';
import Button from '../ui/Button';

interface CartItem {
  name: string;
  quantity: string;
  estimatedCost: string;
  searchQuery: string;
  type: 'tool' | 'material';
  required: boolean;
  checked: boolean;
  expanded: boolean;
}

interface ProjectCartProps {
  tools: Tool[];
  materials: Material[];
  projectTitle: string;
}

const STORES = [
  {
    name: 'Home Depot',
    color: 'bg-orange-600 hover:bg-orange-700',
    icon: '🏠',
    searchUrl: (q: string) => `https://www.homedepot.com/s/${encodeURIComponent(q)}`,
  },
  {
    name: "Lowe's",
    color: 'bg-blue-700 hover:bg-blue-800',
    icon: '🔵',
    searchUrl: (q: string) => `https://www.lowes.com/search?searchTerm=${encodeURIComponent(q)}`,
  },
  {
    name: 'Ace Hardware',
    color: 'bg-red-600 hover:bg-red-700',
    icon: '🔴',
    searchUrl: (q: string) => `https://www.acehardware.com/search?query=${encodeURIComponent(q)}`,
  },
];

export default function ProjectCart({ tools, materials, projectTitle }: ProjectCartProps) {
  const [items, setItems] = useState<CartItem[]>(() => [
    ...tools.map(t => ({
      name: t.name, quantity: '1', estimatedCost: '', searchQuery: t.searchQuery,
      type: 'tool' as const, required: t.required, checked: true, expanded: false,
    })),
    ...materials.map(m => ({
      name: m.name, quantity: m.quantity, estimatedCost: m.estimatedCost, searchQuery: m.searchQuery,
      type: 'material' as const, required: true, checked: true, expanded: false,
    })),
  ]);

  const [copied, setCopied] = useState(false);

  const toggleItem = (index: number) => {
    setItems(prev => prev.map((item, i) => i === index ? { ...item, checked: !item.checked, expanded: !item.checked ? item.expanded : false } : item));
  };

  const toggleExpand = (index: number) => {
    setItems(prev => prev.map((item, i) => i === index ? { ...item, expanded: !item.expanded } : item));
  };

  const checkedItems = items.filter(i => i.checked);

  const buildListText = () => {
    const lines = [`Project Shopping List: ${projectTitle}`, ''];
    const checkedTools = checkedItems.filter(i => i.type === 'tool');
    const checkedMaterials = checkedItems.filter(i => i.type === 'material');
    if (checkedTools.length > 0) {
      lines.push('TOOLS:');
      checkedTools.forEach(t => lines.push(`  - ${t.name}`));
      lines.push('');
    }
    if (checkedMaterials.length > 0) {
      lines.push('MATERIALS:');
      checkedMaterials.forEach(m => lines.push(`  - ${m.name} — Qty: ${m.quantity} (${m.estimatedCost})`));
      lines.push('');
    }
    lines.push(`Total items: ${checkedItems.length}`);
    lines.push('', 'Generated by a. I can fix it');
    return lines.join('\n');
  };

  const buildPriceMatchText = () => {
    const lines = [
      `PRICE MATCH LIST — ${projectTitle}`,
      `Generated: ${new Date().toLocaleDateString()}`,
      '═'.repeat(60),
      '',
    ];

    const addItemSection = (item: CartItem) => {
      lines.push(`▸ ${item.name}${item.quantity !== '1' ? ` (Qty: ${item.quantity})` : ''}`);
      if (item.estimatedCost) lines.push(`  Estimated: ${item.estimatedCost}`);
      lines.push('');
      STORES.forEach(store => {
        lines.push(`  ${store.name}:`);
        lines.push(`    ${store.searchUrl(item.searchQuery)}`);
        lines.push(`    Price: $______`);
        lines.push('');
      });
      lines.push('  ★ Best Price Store: ____________');
      lines.push('─'.repeat(60));
      lines.push('');
    };

    const checkedTools = checkedItems.filter(i => i.type === 'tool');
    const checkedMaterials = checkedItems.filter(i => i.type === 'material');

    if (checkedTools.length > 0) {
      lines.push('TOOLS');
      lines.push('─'.repeat(60));
      checkedTools.forEach(addItemSection);
    }
    if (checkedMaterials.length > 0) {
      lines.push('MATERIALS');
      lines.push('─'.repeat(60));
      checkedMaterials.forEach(addItemSection);
    }

    lines.push('');
    lines.push('═'.repeat(60));
    lines.push('SUMMARY');
    lines.push(`Total items to price match: ${checkedItems.length}`);
    lines.push('');
    lines.push('Tip: Most hardware stores will price match competitors.');
    lines.push('Show this list at checkout to get the best price on each item.');
    lines.push('');
    lines.push('Generated by a. I can fix it');

    return lines.join('\n');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildListText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadList = () => {
    const blob = new Blob([buildListText()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `shopping-list-${projectTitle.toLowerCase().replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPriceMatch = () => {
    const blob = new Blob([buildPriceMatchText()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `price-match-${projectTitle.toLowerCase().replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const renderItem = (item: CartItem, index: number) => (
    <div key={index} className="border border-gray-100 rounded-xl overflow-hidden">
      <div className="flex items-center gap-3 py-2.5 px-3 hover:bg-gray-50 transition-colors">
        <input
          type="checkbox"
          checked={item.checked}
          onChange={() => toggleItem(index)}
          className="w-4 h-4 rounded border-gray-300 text-brand-500 focus:ring-brand-500 flex-shrink-0"
        />
        <button
          onClick={() => item.checked && toggleExpand(index)}
          className={`flex-1 text-left text-sm ${item.checked ? 'text-gray-900 cursor-pointer' : 'text-gray-400 line-through cursor-default'}`}
        >
          {item.name}
        </button>
        <div className="flex items-center gap-2 flex-shrink-0">
          {item.type === 'material' && item.checked && (
            <div className="text-right">
              <div className="text-[10px] text-gray-400">{item.quantity}</div>
              <div className="text-xs font-medium text-green-600">{item.estimatedCost}</div>
            </div>
          )}
          {item.required && <span className="text-[10px] px-1.5 py-0.5 bg-red-50 text-red-600 rounded font-medium">Required</span>}
          {item.checked && (
            <span
              onClick={() => toggleExpand(index)}
              className="text-gray-400 cursor-pointer text-xs select-none"
            >
              {item.expanded ? '▲' : '▼'}
            </span>
          )}
        </div>
      </div>

      {/* Expanded store links */}
      {item.checked && item.expanded && (
        <div className="border-t border-gray-100 bg-gray-50 px-3 py-2 space-y-1.5">
          <p className="text-[10px] text-gray-400 font-medium uppercase tracking-wide">Shop this item:</p>
          {STORES.map(store => (
            <a
              key={store.name}
              href={store.searchUrl(item.searchQuery)}
              target="_blank"
              rel="noopener noreferrer"
              className={`flex items-center justify-between px-3 py-2 rounded-lg text-white text-xs font-medium transition-colors ${store.color}`}
            >
              <span>{store.icon} {store.name}</span>
              <span className="text-white/70">View →</span>
            </a>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <Card>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="font-semibold text-gray-900 flex items-center gap-2">
            <span>🛒</span> Project Cart
          </h3>
          <span className="text-xs text-gray-500">{checkedItems.length} of {items.length} items</span>
        </div>

        {/* Tools */}
        {items.some(i => i.type === 'tool') && (
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Tools</h4>
            <div className="space-y-1.5">
              {items.map((item, i) => item.type === 'tool' ? renderItem(item, i) : null)}
            </div>
          </div>
        )}

        {/* Materials */}
        {items.some(i => i.type === 'material') && (
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Materials</h4>
            <div className="space-y-1.5">
              {items.map((item, i) => item.type === 'material' ? renderItem(item, i) : null)}
            </div>
          </div>
        )}

        {/* Export buttons */}
        <div className="border-t border-gray-100 pt-4 space-y-2">
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" className="flex-1" onClick={handleCopy}>
              {copied ? '✓ Copied!' : '📋 Copy List'}
            </Button>
            <Button variant="secondary" size="sm" className="flex-1" onClick={handleDownloadList}>
              📥 Download List
            </Button>
          </div>
          <button
            onClick={handleDownloadPriceMatch}
            disabled={checkedItems.length === 0}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-gradient-to-r from-orange-500 via-blue-600 to-red-600 text-white text-sm font-semibold transition-opacity disabled:opacity-40 hover:opacity-90"
          >
            💰 Download Price Match List
          </button>
          <p className="text-[10px] text-gray-400 text-center">
            Compare prices across Home Depot, Lowe's &amp; Ace Hardware
          </p>
        </div>
      </div>
    </Card>
  );
}
