import { useState } from 'react';
import type { Tool, Material } from '../../types/analysis';
import Card from '../ui/Card';
import Button from '../ui/Button';
import jsPDF from 'jspdf';

interface CartItem {
  name: string;
  quantity: string;
  estimatedCost: string;
  searchQuery: string;
  type: 'tool' | 'material';
  required: boolean;
  checked: boolean;
  expanded: boolean;
}

interface PriceResult {
  name: string;
  quantity: string;
  homeDepot: number;
  lowes: number;
  ace: number;
  bestStore: string;
  bestPrice: number;
}

interface ProjectCartProps {
  tools: Tool[];
  materials: Material[];
  projectTitle: string;
}

const STORES = [
  {
    name: 'Home Depot',
    color: 'bg-orange-600 hover:bg-orange-700',
    icon: '🏠',
    searchUrl: (q: string) => `https://www.homedepot.com/s/${encodeURIComponent(q)}`,
  },
  {
    name: "Lowe's",
    color: 'bg-blue-700 hover:bg-blue-800',
    icon: '🔵',
    searchUrl: (q: string) => `https://www.lowes.com/search?searchTerm=${encodeURIComponent(q)}`,
  },
  {
    name: 'Ace Hardware',
    color: 'bg-red-600 hover:bg-red-700',
    icon: '🔴',
    searchUrl: (q: string) => `https://www.acehardware.com/search?query=${encodeURIComponent(q)}`,
  },
];

export default function ProjectCart({ tools, materials, projectTitle }: ProjectCartProps) {
  const [items, setItems] = useState<CartItem[]>(() => [
    ...tools.map(t => ({
      name: t.name, quantity: '1', estimatedCost: '', searchQuery: t.searchQuery,
      type: 'tool' as const, required: t.required, checked: true, expanded: false,
    })),
    ...materials.map(m => ({
      name: m.name, quantity: m.quantity, estimatedCost: m.estimatedCost, searchQuery: m.searchQuery,
      type: 'material' as const, required: true, checked: true, expanded: false,
    })),
  ]);

  const [copied, setCopied] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);

  const toggleItem = (index: number) => {
    setItems(prev => prev.map((item, i) => i === index ? { ...item, checked: !item.checked, expanded: !item.checked ? item.expanded : false } : item));
  };

  const toggleExpand = (index: number) => {
    setItems(prev => prev.map((item, i) => i === index ? { ...item, expanded: !item.expanded } : item));
  };

  const checkedItems = items.filter(i => i.checked);

  const buildListText = () => {
    const lines = [`Project Shopping List: ${projectTitle}`, ''];
    const checkedTools = checkedItems.filter(i => i.type === 'tool');
    const checkedMaterials = checkedItems.filter(i => i.type === 'material');
    if (checkedTools.length > 0) {
      lines.push('TOOLS:');
      checkedTools.forEach(t => lines.push(`  - ${t.name}`));
      lines.push('');
    }
    if (checkedMaterials.length > 0) {
      lines.push('MATERIALS:');
      checkedMaterials.forEach(m => lines.push(`  - ${m.name} — Qty: ${m.quantity} (${m.estimatedCost})`));
      lines.push('');
    }
    lines.push(`Total items: ${checkedItems.length}`);
    lines.push('', 'Generated by a. I can fix it');
    return lines.join('\n');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildListText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadList = () => {
    const blob = new Blob([buildListText()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `shopping-list-${projectTitle.toLowerCase().replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPriceMatch = async () => {
    if (checkedItems.length === 0) return;
    setGeneratingPdf(true);

    try {
      // Fetch estimated prices from AI
      const res = await fetch('/api/prices', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          items: checkedItems.map(i => ({
            name: i.name,
            searchQuery: i.searchQuery,
            quantity: i.quantity,
          })),
        }),
      });

      if (!res.ok) throw new Error('Price estimation failed');
      const { prices } = await res.json() as { prices: PriceResult[] };

      generatePricePdf(prices);
    } catch (err) {
      console.error('Price match error:', err);
      // Fallback: generate PDF without prices
      const fallback: PriceResult[] = checkedItems.map(i => ({
        name: i.name, quantity: i.quantity,
        homeDepot: 0, lowes: 0, ace: 0,
        bestStore: 'Check stores', bestPrice: 0,
      }));
      generatePricePdf(fallback);
    } finally {
      setGeneratingPdf(false);
    }
  };

  const generatePricePdf = (prices: PriceResult[]) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const colWidth = pageWidth - margin * 2;
    let y = margin;

    // Header background
    doc.setFillColor(30, 58, 95); // dark blue
    doc.rect(0, 0, pageWidth, 45, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Price Match List', margin, 22);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(projectTitle, margin, 33);
    doc.setFontSize(9);
    doc.text(`Generated ${new Date().toLocaleDateString()} by a. I can fix it`, margin, 41);

    y = 55;

    // Summary bar
    const totalSavings = prices.reduce((sum, p) => {
      const maxPrice = Math.max(p.homeDepot, p.lowes, p.ace);
      return sum + (maxPrice - p.bestPrice);
    }, 0);
    const totalBestCost = prices.reduce((sum, p) => {
      const qty = parseInt(p.quantity) || 1;
      return sum + p.bestPrice * qty;
    }, 0);

    doc.setFillColor(236, 253, 245); // green-50
    doc.roundedRect(margin, y, colWidth, 22, 3, 3, 'F');
    doc.setTextColor(22, 101, 52);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Estimated Best Total: $${totalBestCost.toFixed(2)}`, margin + 5, y + 10);
    if (totalSavings > 0) {
      doc.text(`Potential Savings: $${totalSavings.toFixed(2)} vs. most expensive option`, margin + 5, y + 18);
    }

    y += 30;

    // Column headers
    doc.setFillColor(241, 245, 249); // gray-100
    doc.rect(margin, y, colWidth, 10, 'F');
    doc.setTextColor(71, 85, 105);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('ITEM', margin + 3, y + 7);
    doc.text('QTY', margin + 85, y + 7);
    doc.text('BEST STORE', margin + 100, y + 7);
    doc.text('BEST PRICE', margin + 145, y + 7);
    y += 13;

    // Items
    prices.forEach((item, i) => {
      // Check if we need a new page
      if (y > 260) {
        doc.addPage();
        y = margin;
      }

      const qty = parseInt(item.quantity) || 1;
      const rowH = 18;

      // Alternating row background
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, y, colWidth, rowH, 'F');
      }

      // Item name
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      const name = item.name.length > 35 ? item.name.substring(0, 35) + '...' : item.name;
      doc.text(name, margin + 3, y + 7);

      // Store-by-store prices on second line (smaller)
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(120, 130, 140);
      const priceComparison = `HD: $${item.homeDepot.toFixed(2)}  |  Lowe's: $${item.lowes.toFixed(2)}  |  Ace: $${item.ace.toFixed(2)}`;
      doc.text(priceComparison, margin + 3, y + 14);

      // Quantity
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text(String(qty), margin + 88, y + 7);

      // Best store with color coding
      const storeColors: Record<string, [number, number, number]> = {
        'Home Depot': [234, 88, 12],
        "Lowe's": [29, 78, 216],
        'Ace Hardware': [220, 38, 38],
      };
      const storeColor = storeColors[item.bestStore] || [71, 85, 105];
      doc.setTextColor(...storeColor);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text(item.bestStore, margin + 100, y + 7);

      // Best price
      doc.setTextColor(22, 101, 52); // green
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      const totalPrice = item.bestPrice * qty;
      doc.text(`$${totalPrice.toFixed(2)}`, margin + 148, y + 7);

      // Per-unit if qty > 1
      if (qty > 1) {
        doc.setFontSize(7);
        doc.setTextColor(120, 130, 140);
        doc.setFont('helvetica', 'normal');
        doc.text(`($${item.bestPrice.toFixed(2)} ea.)`, margin + 148, y + 14);
      }

      y += rowH + 2;
    });

    // Footer
    y += 8;
    if (y > 255) { doc.addPage(); y = margin; }

    doc.setDrawColor(203, 213, 225);
    doc.line(margin, y, margin + colWidth, y);
    y += 8;

    doc.setTextColor(100, 116, 139);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text('Prices are AI-estimated and may vary. Show this list at checkout for price matching.', margin, y);
    y += 5;
    doc.text('Most hardware stores will match competitor prices — ask at the register.', margin, y);
    y += 10;

    doc.setTextColor(37, 99, 235);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('Generated by a. I can fix it', margin, y);

    // Save
    doc.save(`price-match-${projectTitle.toLowerCase().replace(/\s+/g, '-')}.pdf`);
  };

  const renderItem = (item: CartItem, index: number) => (
    <div key={index} className="border border-gray-100 rounded-xl overflow-hidden">
      <div className="flex items-center gap-3 py-2.5 px-3 hover:bg-gray-50 transition-colors">
        <input
          type="checkbox"
          checked={item.checked}
          onChange={() => toggleItem(index)}
          className="w-4 h-4 rounded border-gray-300 text-brand-500 focus:ring-brand-500 flex-shrink-0"
        />
        <button
          onClick={() => item.checked && toggleExpand(index)}
          className={`flex-1 text-left text-sm ${item.checked ? 'text-gray-900 cursor-pointer' : 'text-gray-400 line-through cursor-default'}`}
        >
          {item.name}
        </button>
        <div className="flex items-center gap-2 flex-shrink-0">
          {item.type === 'material' && item.checked && (
            <div className="text-right">
              <div className="text-[10px] text-gray-400">{item.quantity}</div>
              <div className="text-xs font-medium text-green-600">{item.estimatedCost}</div>
            </div>
          )}
          {item.required && <span className="text-[10px] px-1.5 py-0.5 bg-red-50 text-red-600 rounded font-medium">Required</span>}
          {item.checked && (
            <span
              onClick={() => toggleExpand(index)}
              className="text-gray-400 cursor-pointer text-xs select-none"
            >
              {item.expanded ? '▲' : '▼'}
            </span>
          )}
        </div>
      </div>

      {/* Expanded store links */}
      {item.checked && item.expanded && (
        <div className="border-t border-gray-100 bg-gray-50 px-3 py-2 space-y-1.5">
          <p className="text-[10px] text-gray-400 font-medium uppercase tracking-wide">Shop this item:</p>
          {STORES.map(store => (
            <a
              key={store.name}
              href={store.searchUrl(item.searchQuery)}
              target="_blank"
              rel="noopener noreferrer"
              className={`flex items-center justify-between px-3 py-2 rounded-lg text-white text-xs font-medium transition-colors ${store.color}`}
            >
              <span>{store.icon} {store.name}</span>
              <span className="text-white/70">View →</span>
            </a>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <Card>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="font-semibold text-gray-900 flex items-center gap-2">
            <span>🛒</span> Project Cart
          </h3>
          <span className="text-xs text-gray-500">{checkedItems.length} of {items.length} items</span>
        </div>

        {/* Tools */}
        {items.some(i => i.type === 'tool') && (
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Tools</h4>
            <div className="space-y-1.5">
              {items.map((item, i) => item.type === 'tool' ? renderItem(item, i) : null)}
            </div>
          </div>
        )}

        {/* Materials */}
        {items.some(i => i.type === 'material') && (
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Materials</h4>
            <div className="space-y-1.5">
              {items.map((item, i) => item.type === 'material' ? renderItem(item, i) : null)}
            </div>
          </div>
        )}

        {/* Export buttons */}
        <div className="border-t border-gray-100 pt-4 space-y-2">
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" className="flex-1" onClick={handleCopy}>
              {copied ? '✓ Copied!' : '📋 Copy List'}
            </Button>
            <Button variant="secondary" size="sm" className="flex-1" onClick={handleDownloadList}>
              📥 Download List
            </Button>
          </div>
          <button
            onClick={handleDownloadPriceMatch}
            disabled={checkedItems.length === 0 || generatingPdf}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-gradient-to-r from-orange-500 via-blue-600 to-red-600 text-white text-sm font-semibold transition-opacity disabled:opacity-40 hover:opacity-90"
          >
            {generatingPdf ? (
              <>
                <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
                Comparing prices...
              </>
            ) : (
              '💰 Download Price Match List (PDF)'
            )}
          </button>
          <p className="text-[10px] text-gray-400 text-center">
            AI-estimated best prices across Home Depot, Lowe's &amp; Ace Hardware
          </p>
        </div>
      </div>
    </Card>
  );
}
